// Generated by scripts/generate-credits.mjs — do not edit. Refresh with `pnpm credits`.
export type CreditEntry = { name: string; version: string; license: string };

export const CREDITS: CreditEntry[] = [
  {
    name: '@antfu/install-pkg',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: '@anthropic-ai/sdk',
    version: '0.91.1',
    license: 'MIT',
  },
  {
    name: '@astrojs/compiler-binding',
    version: '0.3.1',
    license: 'MIT',
  },
  {
    name: '@astrojs/compiler-binding-darwin-arm64',
    version: '0.3.1',
    license: 'MIT',
  },
  {
    name: '@astrojs/compiler-rs',
    version: '0.3.1',
    license: 'MIT',
  },
  {
    name: '@astrojs/internal-helpers',
    version: '0.10.1',
    license: 'MIT',
  },
  {
    name: '@astrojs/markdown-satteri',
    version: '0.3.4',
    license: 'MIT',
  },
  {
    name: '@astrojs/prism',
    version: '4.0.2',
    license: 'MIT',
  },
  {
    name: '@astrojs/sitemap',
    version: '3.7.3',
    license: 'MIT',
  },
  {
    name: '@astrojs/telemetry',
    version: '3.3.3',
    license: 'MIT',
  },
  {
    name: '@aws-crypto/sha256-browser',
    version: '5.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-crypto/sha256-js',
    version: '5.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-crypto/supports-web-crypto',
    version: '5.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-crypto/util',
    version: '5.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/client-bedrock-runtime',
    version: '3.1048.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/core',
    version: '3.975.3',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-env',
    version: '3.972.59',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-http',
    version: '3.972.61',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-ini',
    version: '3.973.4',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-login',
    version: '3.972.66',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-node',
    version: '3.972.70',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-process',
    version: '3.972.59',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-sso',
    version: '3.973.3',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/credential-provider-web-identity',
    version: '3.972.65',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/eventstream-handler-node',
    version: '3.972.29',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/middleware-eventstream',
    version: '3.972.24',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/middleware-websocket',
    version: '3.972.41',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/nested-clients',
    version: '3.997.33',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/signature-v4-multi-region',
    version: '3.996.41',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/token-providers',
    version: '3.1048.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/token-providers',
    version: '3.1088.0',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/types',
    version: '3.974.2',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/util-locate-window',
    version: '3.965.8',
    license: 'Apache-2.0',
  },
  {
    name: '@aws-sdk/xml-builder',
    version: '3.972.36',
    license: 'Apache-2.0',
  },
  {
    name: '@aws/lambda-invoke-store',
    version: '0.3.0',
    license: 'Apache-2.0',
  },
  {
    name: '@babel/helper-string-parser',
    version: '7.29.7',
    license: 'MIT',
  },
  {
    name: '@babel/helper-validator-identifier',
    version: '7.29.7',
    license: 'MIT',
  },
  {
    name: '@babel/parser',
    version: '7.29.7',
    license: 'MIT',
  },
  {
    name: '@babel/runtime',
    version: '7.29.7',
    license: 'MIT',
  },
  {
    name: '@babel/types',
    version: '7.29.7',
    license: 'MIT',
  },
  {
    name: '@base-ui/react',
    version: '1.6.0',
    license: 'MIT',
  },
  {
    name: '@base-ui/utils',
    version: '0.3.1',
    license: 'MIT',
  },
  {
    name: '@braintree/sanitize-url',
    version: '7.1.2',
    license: 'MIT',
  },
  {
    name: '@bruits/satteri-darwin-arm64',
    version: '0.9.5',
    license: 'MIT',
  },
  {
    name: '@capsizecss/unpack',
    version: '4.0.1',
    license: 'MIT',
  },
  {
    name: '@chevrotain/types',
    version: '11.1.2',
    license: 'Apache-2.0',
  },
  {
    name: '@clack/core',
    version: '1.4.3',
    license: 'MIT',
  },
  {
    name: '@clack/prompts',
    version: '1.7.0',
    license: 'MIT',
  },
  {
    name: '@codemirror/language',
    version: '6.12.4',
    license: 'MIT',
  },
  {
    name: '@codemirror/state',
    version: '6.7.1',
    license: 'MIT',
  },
  {
    name: '@codemirror/view',
    version: '6.43.6',
    license: 'MIT',
  },
  {
    name: '@earendil-works/pi-agent-core',
    version: '0.84.1',
    license: 'MIT',
  },
  {
    name: '@earendil-works/pi-ai',
    version: '0.84.1',
    license: 'MIT',
  },
  {
    name: '@earendil-works/pi-telemetry',
    version: '0.84.1',
    license: 'MIT',
  },
  {
    name: '@electron-internal/extract-zip',
    version: '1.0.4',
    license: 'BSD-2-Clause',
  },
  {
    name: '@electron/get',
    version: '5.0.0',
    license: 'MIT',
  },
  {
    name: '@esbuild/darwin-arm64',
    version: '0.28.1',
    license: 'MIT',
  },
  {
    name: '@ffmpeg-installer/darwin-arm64',
    version: '4.1.5',
    license: 'https://git.ffmpeg.org/gitweb/ffmpeg.git/blob_plain/HEAD:/LICENSE.md',
  },
  {
    name: '@ffmpeg-installer/ffmpeg',
    version: '1.1.0',
    license: 'LGPL-2.1',
  },
  {
    name: '@ffprobe-installer/darwin-arm64',
    version: '5.0.1',
    license: 'LGPL-2.1',
  },
  {
    name: '@ffprobe-installer/ffprobe',
    version: '2.1.2',
    license: 'LGPL-2.1',
  },
  {
    name: '@floating-ui/core',
    version: '1.8.0',
    license: 'MIT',
  },
  {
    name: '@floating-ui/dom',
    version: '1.8.0',
    license: 'MIT',
  },
  {
    name: '@floating-ui/react-dom',
    version: '2.1.9',
    license: 'MIT',
  },
  {
    name: '@floating-ui/utils',
    version: '0.2.12',
    license: 'MIT',
  },
  {
    name: '@google/genai',
    version: '1.52.0',
    license: 'Apache-2.0',
  },
  {
    name: '@hono/node-server',
    version: '2.0.10',
    license: 'MIT',
  },
  {
    name: '@iconify/types',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: '@iconify/utils',
    version: '3.1.4',
    license: 'MIT',
  },
  {
    name: '@img/colour',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: '@img/sharp-darwin-arm64',
    version: '0.35.3',
    license: 'Apache-2.0',
  },
  {
    name: '@img/sharp-libvips-darwin-arm64',
    version: '1.3.2',
    license: 'LGPL-3.0-or-later',
  },
  {
    name: '@innei/message-engine',
    version: '0.2.0',
    license: 'MIT',
  },
  {
    name: '@isaacs/fs-minipass',
    version: '4.0.1',
    license: 'ISC',
  },
  {
    name: '@jitl/quickjs-ffi-types',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: '@jitl/quickjs-wasmfile-debug-asyncify',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: '@jitl/quickjs-wasmfile-debug-sync',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: '@jitl/quickjs-wasmfile-release-asyncify',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: '@jitl/quickjs-wasmfile-release-sync',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: '@jridgewell/gen-mapping',
    version: '0.3.13',
    license: 'MIT',
  },
  {
    name: '@jridgewell/resolve-uri',
    version: '3.1.2',
    license: 'MIT',
  },
  {
    name: '@jridgewell/sourcemap-codec',
    version: '1.5.5',
    license: 'MIT',
  },
  {
    name: '@jridgewell/trace-mapping',
    version: '0.3.31',
    license: 'MIT',
  },
  {
    name: '@lezer/common',
    version: '1.5.2',
    license: 'MIT',
  },
  {
    name: '@lezer/highlight',
    version: '1.2.3',
    license: 'MIT',
  },
  {
    name: '@lezer/lr',
    version: '1.4.10',
    license: 'MIT',
  },
  {
    name: '@marijn/find-cluster-break',
    version: '1.0.3',
    license: 'MIT',
  },
  {
    name: '@mermaid-js/parser',
    version: '1.2.0',
    license: 'MIT',
  },
  {
    name: '@mistralai/mistralai',
    version: '2.2.6',
    license: 'Apache-2.0',
  },
  {
    name: '@opentelemetry/api',
    version: '1.9.0',
    license: 'Apache-2.0',
  },
  {
    name: '@opentelemetry/semantic-conventions',
    version: '1.43.0',
    license: 'Apache-2.0',
  },
  {
    name: '@oslojs/encoding',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: '@oxc-project/types',
    version: '0.139.0',
    license: 'MIT',
  },
  {
    name: '@posthog/core',
    version: '1.45.1',
    license: 'MIT',
  },
  {
    name: '@posthog/types',
    version: '1.398.0',
    license: 'MIT',
  },
  {
    name: '@protobufjs/aspromise',
    version: '1.1.2',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/base64',
    version: '1.1.2',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/codegen',
    version: '2.0.5',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/eventemitter',
    version: '1.1.1',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/fetch',
    version: '1.1.1',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/float',
    version: '1.0.2',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/path',
    version: '1.1.2',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/pool',
    version: '1.1.0',
    license: 'BSD-3-Clause',
  },
  {
    name: '@protobufjs/utf8',
    version: '1.1.2',
    license: 'BSD-3-Clause',
  },
  {
    name: '@puppeteer/browsers',
    version: '3.0.6',
    license: 'Apache-2.0',
  },
  {
    name: '@reduxjs/toolkit',
    version: '2.12.0',
    license: 'MIT',
  },
  {
    name: '@revideo/2d',
    version: '0.11.0',
    license: 'MIT',
  },
  {
    name: '@revideo/core',
    version: '0.11.0',
    license: 'MIT',
  },
  {
    name: '@revideo/ffmpeg',
    version: '0.11.0',
    license: 'MIT',
  },
  {
    name: '@revideo/renderer',
    version: '0.11.0',
    license: 'MIT',
  },
  {
    name: '@revideo/telemetry',
    version: '0.11.0',
    license: 'MIT',
  },
  {
    name: '@rive-app/canvas-advanced',
    version: '2.7.3',
    license: 'MIT',
  },
  {
    name: '@rolldown/binding-darwin-arm64',
    version: '1.1.5',
    license: 'MIT',
  },
  {
    name: '@rolldown/pluginutils',
    version: '1.0.1',
    license: 'MIT',
  },
  {
    name: '@rollup/pluginutils',
    version: '5.4.0',
    license: 'MIT',
  },
  {
    name: '@shikijs/core',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/engine-javascript',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/engine-oniguruma',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/langs',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/primitive',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/themes',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/types',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: '@shikijs/vscode-textmate',
    version: '10.0.2',
    license: 'MIT',
  },
  {
    name: '@smithy/core',
    version: '3.29.5',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/credential-provider-imds',
    version: '4.4.10',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/fetch-http-handler',
    version: '5.6.7',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/is-array-buffer',
    version: '2.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/node-http-handler',
    version: '4.7.3',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/node-http-handler',
    version: '4.9.7',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/signature-v4',
    version: '5.6.6',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/types',
    version: '4.16.1',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/util-buffer-from',
    version: '2.2.0',
    license: 'Apache-2.0',
  },
  {
    name: '@smithy/util-utf8',
    version: '2.3.0',
    license: 'Apache-2.0',
  },
  {
    name: '@standard-schema/spec',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: '@standard-schema/utils',
    version: '0.3.0',
    license: 'MIT',
  },
  {
    name: '@stylexjs/stylex',
    version: '0.19.0',
    license: 'MIT',
  },
  {
    name: '@tanstack/query-core',
    version: '5.101.2',
    license: 'MIT',
  },
  {
    name: '@tanstack/query-persist-client-core',
    version: '5.101.2',
    license: 'MIT',
  },
  {
    name: '@tanstack/query-sync-storage-persister',
    version: '5.101.2',
    license: 'MIT',
  },
  {
    name: '@tanstack/react-query',
    version: '5.101.2',
    license: 'MIT',
  },
  {
    name: '@tanstack/react-query-persist-client',
    version: '5.101.2',
    license: 'MIT',
  },
  {
    name: '@tsuki-hono/common',
    version: '0.0.5',
    license: 'MIT',
  },
  {
    name: '@tsuki-hono/core',
    version: '0.0.5',
    license: 'MIT',
  },
  {
    name: '@types/d3',
    version: '7.4.3',
    license: 'MIT',
  },
  {
    name: '@types/d3-array',
    version: '3.2.2',
    license: 'MIT',
  },
  {
    name: '@types/d3-axis',
    version: '3.0.6',
    license: 'MIT',
  },
  {
    name: '@types/d3-brush',
    version: '3.0.6',
    license: 'MIT',
  },
  {
    name: '@types/d3-chord',
    version: '3.0.6',
    license: 'MIT',
  },
  {
    name: '@types/d3-color',
    version: '3.1.3',
    license: 'MIT',
  },
  {
    name: '@types/d3-contour',
    version: '3.0.6',
    license: 'MIT',
  },
  {
    name: '@types/d3-delaunay',
    version: '6.0.4',
    license: 'MIT',
  },
  {
    name: '@types/d3-dispatch',
    version: '3.0.7',
    license: 'MIT',
  },
  {
    name: '@types/d3-drag',
    version: '3.0.7',
    license: 'MIT',
  },
  {
    name: '@types/d3-dsv',
    version: '3.0.7',
    license: 'MIT',
  },
  {
    name: '@types/d3-ease',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: '@types/d3-fetch',
    version: '3.0.7',
    license: 'MIT',
  },
  {
    name: '@types/d3-force',
    version: '3.0.10',
    license: 'MIT',
  },
  {
    name: '@types/d3-format',
    version: '3.0.4',
    license: 'MIT',
  },
  {
    name: '@types/d3-geo',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: '@types/d3-hierarchy',
    version: '3.1.7',
    license: 'MIT',
  },
  {
    name: '@types/d3-interpolate',
    version: '3.0.4',
    license: 'MIT',
  },
  {
    name: '@types/d3-path',
    version: '3.1.1',
    license: 'MIT',
  },
  {
    name: '@types/d3-polygon',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: '@types/d3-quadtree',
    version: '3.0.6',
    license: 'MIT',
  },
  {
    name: '@types/d3-random',
    version: '3.0.4',
    license: 'MIT',
  },
  {
    name: '@types/d3-scale',
    version: '4.0.9',
    license: 'MIT',
  },
  {
    name: '@types/d3-scale-chromatic',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: '@types/d3-selection',
    version: '3.0.11',
    license: 'MIT',
  },
  {
    name: '@types/d3-shape',
    version: '3.1.8',
    license: 'MIT',
  },
  {
    name: '@types/d3-time',
    version: '3.0.4',
    license: 'MIT',
  },
  {
    name: '@types/d3-time-format',
    version: '4.0.3',
    license: 'MIT',
  },
  {
    name: '@types/d3-timer',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: '@types/d3-transition',
    version: '3.0.9',
    license: 'MIT',
  },
  {
    name: '@types/d3-zoom',
    version: '3.0.8',
    license: 'MIT',
  },
  {
    name: '@types/debug',
    version: '4.1.13',
    license: 'MIT',
  },
  {
    name: '@types/estree',
    version: '1.0.9',
    license: 'MIT',
  },
  {
    name: '@types/estree-jsx',
    version: '1.0.5',
    license: 'MIT',
  },
  {
    name: '@types/geojson',
    version: '7946.0.16',
    license: 'MIT',
  },
  {
    name: '@types/hast',
    version: '2.3.10',
    license: 'MIT',
  },
  {
    name: '@types/hast',
    version: '3.0.5',
    license: 'MIT',
  },
  {
    name: '@types/mdast',
    version: '4.0.4',
    license: 'MIT',
  },
  {
    name: '@types/ms',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: '@types/nlcst',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: '@types/node',
    version: '24.13.3',
    license: 'MIT',
  },
  {
    name: '@types/node',
    version: '26.1.1',
    license: 'MIT',
  },
  {
    name: '@types/react',
    version: '19.2.17',
    license: 'MIT',
  },
  {
    name: '@types/retry',
    version: '0.12.0',
    license: 'MIT',
  },
  {
    name: '@types/sax',
    version: '1.2.7',
    license: 'MIT',
  },
  {
    name: '@types/trusted-types',
    version: '2.0.7',
    license: 'MIT',
  },
  {
    name: '@types/unist',
    version: '2.0.11',
    license: 'MIT',
  },
  {
    name: '@types/unist',
    version: '3.0.3',
    license: 'MIT',
  },
  {
    name: '@types/use-sync-external-store',
    version: '0.0.6',
    license: 'MIT',
  },
  {
    name: '@ungap/structured-clone',
    version: '1.3.3',
    license: 'ISC',
  },
  {
    name: '@upsetjs/venn.js',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: '@wooorm/starry-night',
    version: '1.7.0',
    license: 'MIT',
  },
  {
    name: '@xmldom/xmldom',
    version: '0.9.10',
    license: 'MIT',
  },
  {
    name: 'abbrev',
    version: '5.0.0',
    license: 'ISC',
  },
  {
    name: 'agent-base',
    version: '7.1.4',
    license: 'MIT',
  },
  {
    name: 'am-i-vibing',
    version: '0.4.0',
    license: 'MIT',
  },
  {
    name: 'ansi-regex',
    version: '6.2.2',
    license: 'MIT',
  },
  {
    name: 'ansi-styles',
    version: '6.2.3',
    license: 'MIT',
  },
  {
    name: 'any-promise',
    version: '1.3.0',
    license: 'MIT',
  },
  {
    name: 'anymatch',
    version: '3.1.3',
    license: 'ISC',
  },
  {
    name: 'arg',
    version: '5.0.2',
    license: 'MIT',
  },
  {
    name: 'argparse',
    version: '2.0.1',
    license: 'Python-2.0',
  },
  {
    name: 'aria-query',
    version: '5.3.2',
    license: 'Apache-2.0',
  },
  {
    name: 'astro',
    version: '7.1.3',
    license: 'MIT',
  },
  {
    name: 'async',
    version: '0.2.10',
    license: 'MIT',
  },
  {
    name: 'axobject-query',
    version: '4.1.0',
    license: 'Apache-2.0',
  },
  {
    name: 'bail',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'base64-js',
    version: '1.5.1',
    license: 'MIT',
  },
  {
    name: 'bignumber.js',
    version: '9.3.1',
    license: 'MIT',
  },
  {
    name: 'boolbase',
    version: '1.0.0',
    license: 'ISC',
  },
  {
    name: 'bowser',
    version: '2.14.1',
    license: 'MIT',
  },
  {
    name: 'buffer-equal-constant-time',
    version: '1.0.1',
    license: 'BSD-3-Clause',
  },
  {
    name: 'ccount',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'character-entities',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'character-entities-html4',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'character-entities-legacy',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'character-reference-invalid',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'chokidar',
    version: '5.0.0',
    license: 'MIT',
  },
  {
    name: 'chownr',
    version: '3.0.0',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'chromium-bidi',
    version: '17.0.2',
    license: 'Apache-2.0',
  },
  {
    name: 'ci-info',
    version: '4.4.0',
    license: 'MIT',
  },
  {
    name: 'cliui',
    version: '9.0.1',
    license: 'ISC',
  },
  {
    name: 'clsx',
    version: '2.1.1',
    license: 'MIT',
  },
  {
    name: 'code-fns',
    version: '0.8.2',
    license: 'MIT',
  },
  {
    name: 'comma-separated-tokens',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'commander',
    version: '11.1.0',
    license: 'MIT',
  },
  {
    name: 'commander',
    version: '13.1.0',
    license: 'MIT',
  },
  {
    name: 'commander',
    version: '4.1.1',
    license: 'MIT',
  },
  {
    name: 'commander',
    version: '7.2.0',
    license: 'MIT',
  },
  {
    name: 'commander',
    version: '8.3.0',
    license: 'MIT',
  },
  {
    name: 'common-ancestor-path',
    version: '2.0.0',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'cookie',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'cookie-es',
    version: '1.2.3',
    license: 'MIT',
  },
  {
    name: 'cookie-es',
    version: '3.1.1',
    license: 'MIT',
  },
  {
    name: 'cose-base',
    version: '1.0.3',
    license: 'MIT',
  },
  {
    name: 'cose-base',
    version: '2.2.0',
    license: 'MIT',
  },
  {
    name: 'crelt',
    version: '1.0.7',
    license: 'MIT',
  },
  {
    name: 'crossws',
    version: '0.3.5',
    license: 'MIT',
  },
  {
    name: 'css-mediaquery',
    version: '0.1.2',
    license: 'BSD',
  },
  {
    name: 'css-select',
    version: '5.2.2',
    license: 'BSD-2-Clause',
  },
  {
    name: 'css-tree',
    version: '2.2.1',
    license: 'MIT',
  },
  {
    name: 'css-tree',
    version: '3.2.1',
    license: 'MIT',
  },
  {
    name: 'css-what',
    version: '6.2.2',
    license: 'BSD-2-Clause',
  },
  {
    name: 'csso',
    version: '5.0.5',
    license: 'MIT',
  },
  {
    name: 'csstype',
    version: '3.2.3',
    license: 'MIT',
  },
  {
    name: 'culori',
    version: '4.0.2',
    license: 'MIT',
  },
  {
    name: 'cytoscape',
    version: '3.34.0',
    license: 'MIT',
  },
  {
    name: 'cytoscape-cose-bilkent',
    version: '4.1.0',
    license: 'MIT',
  },
  {
    name: 'cytoscape-fcose',
    version: '2.2.0',
    license: 'MIT',
  },
  {
    name: 'd3',
    version: '7.9.0',
    license: 'ISC',
  },
  {
    name: 'd3-array',
    version: '2.12.1',
    license: 'BSD-3-Clause',
  },
  {
    name: 'd3-array',
    version: '3.2.4',
    license: 'ISC',
  },
  {
    name: 'd3-axis',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'd3-brush',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'd3-chord',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-color',
    version: '3.1.0',
    license: 'ISC',
  },
  {
    name: 'd3-contour',
    version: '4.0.2',
    license: 'ISC',
  },
  {
    name: 'd3-delaunay',
    version: '6.0.4',
    license: 'ISC',
  },
  {
    name: 'd3-dispatch',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-drag',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'd3-dsv',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-ease',
    version: '3.0.1',
    license: 'BSD-3-Clause',
  },
  {
    name: 'd3-fetch',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-force',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'd3-format',
    version: '3.1.2',
    license: 'ISC',
  },
  {
    name: 'd3-geo',
    version: '3.1.1',
    license: 'ISC',
  },
  {
    name: 'd3-hierarchy',
    version: '3.1.2',
    license: 'ISC',
  },
  {
    name: 'd3-interpolate',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-path',
    version: '1.0.9',
    license: 'BSD-3-Clause',
  },
  {
    name: 'd3-path',
    version: '3.1.0',
    license: 'ISC',
  },
  {
    name: 'd3-polygon',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-quadtree',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-random',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-sankey',
    version: '0.12.3',
    license: 'BSD-3-Clause',
  },
  {
    name: 'd3-scale',
    version: '4.0.2',
    license: 'ISC',
  },
  {
    name: 'd3-scale-chromatic',
    version: '3.1.0',
    license: 'ISC',
  },
  {
    name: 'd3-selection',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'd3-shape',
    version: '1.3.7',
    license: 'BSD-3-Clause',
  },
  {
    name: 'd3-shape',
    version: '3.2.0',
    license: 'ISC',
  },
  {
    name: 'd3-time',
    version: '3.1.0',
    license: 'ISC',
  },
  {
    name: 'd3-time-format',
    version: '4.1.0',
    license: 'ISC',
  },
  {
    name: 'd3-timer',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-transition',
    version: '3.0.1',
    license: 'ISC',
  },
  {
    name: 'd3-zoom',
    version: '3.0.0',
    license: 'ISC',
  },
  {
    name: 'dagre-d3-es',
    version: '7.0.14',
    license: 'MIT',
  },
  {
    name: 'data-uri-to-buffer',
    version: '4.0.1',
    license: 'MIT',
  },
  {
    name: 'dayjs',
    version: '1.11.21',
    license: 'MIT',
  },
  {
    name: 'debug',
    version: '4.4.3',
    license: 'MIT',
  },
  {
    name: 'decimal.js-light',
    version: '2.5.1',
    license: 'MIT',
  },
  {
    name: 'decode-named-character-reference',
    version: '1.3.0',
    license: 'MIT',
  },
  {
    name: 'defu',
    version: '6.1.7',
    license: 'MIT',
  },
  {
    name: 'delaunator',
    version: '5.1.0',
    license: 'ISC',
  },
  {
    name: 'dequal',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'destr',
    version: '2.0.5',
    license: 'MIT',
  },
  {
    name: 'detect-libc',
    version: '2.1.2',
    license: 'Apache-2.0',
  },
  {
    name: 'devalue',
    version: '5.8.1',
    license: 'MIT',
  },
  {
    name: 'devlop',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: 'devtools-protocol',
    version: '0.0.1653615',
    license: 'BSD-3-Clause',
  },
  {
    name: 'diff',
    version: '8.0.4',
    license: 'BSD-3-Clause',
  },
  {
    name: 'dom-serializer',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'domelementtype',
    version: '2.3.0',
    license: 'BSD-2-Clause',
  },
  {
    name: 'domhandler',
    version: '5.0.3',
    license: 'BSD-2-Clause',
  },
  {
    name: 'dompurify',
    version: '3.4.12',
    license: '(MPL-2.0 OR Apache-2.0)',
  },
  {
    name: 'domutils',
    version: '3.2.2',
    license: 'BSD-2-Clause',
  },
  {
    name: 'drizzle-orm',
    version: '1.0.0-rc.4',
    license: 'Apache-2.0',
  },
  {
    name: 'dset',
    version: '3.1.4',
    license: 'MIT',
  },
  {
    name: 'ecdsa-sig-formatter',
    version: '1.0.11',
    license: 'Apache-2.0',
  },
  {
    name: 'electron',
    version: '43.1.1',
    license: 'MIT',
  },
  {
    name: 'electron-ipc-decorator',
    version: '1.0.1',
    license: 'MIT',
  },
  {
    name: 'electron-sparkle-updater',
    version: '0.1.0',
    license: 'MIT',
  },
  {
    name: 'emoji-regex',
    version: '10.6.0',
    license: 'MIT',
  },
  {
    name: 'entities',
    version: '4.5.0',
    license: 'BSD-2-Clause',
  },
  {
    name: 'entities',
    version: '6.0.1',
    license: 'BSD-2-Clause',
  },
  {
    name: 'env-paths',
    version: '2.2.1',
    license: 'MIT',
  },
  {
    name: 'env-paths',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'es-module-lexer',
    version: '2.3.1',
    license: 'MIT',
  },
  {
    name: 'es-toolkit',
    version: '1.49.0',
    license: 'MIT',
  },
  {
    name: 'esbuild',
    version: '0.28.1',
    license: 'MIT',
  },
  {
    name: 'escalade',
    version: '3.2.0',
    license: 'MIT',
  },
  {
    name: 'escape-string-regexp',
    version: '5.0.0',
    license: 'MIT',
  },
  {
    name: 'esm',
    version: '3.2.25',
    license: 'MIT',
  },
  {
    name: 'estree-util-is-identifier-name',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'estree-walker',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'eventemitter3',
    version: '5.0.4',
    license: 'MIT',
  },
  {
    name: 'exponential-backoff',
    version: '3.1.3',
    license: 'Apache-2.0',
  },
  {
    name: 'extend',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: 'fancy-canvas',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'fast-string-truncated-width',
    version: '3.0.3',
    license: 'MIT',
  },
  {
    name: 'fast-string-width',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: 'fast-wrap-ansi',
    version: '0.2.2',
    license: 'MIT',
  },
  {
    name: 'fdir',
    version: '6.5.0',
    license: 'MIT',
  },
  {
    name: 'fetch-blob',
    version: '3.2.0',
    license: 'MIT',
  },
  {
    name: 'flattie',
    version: '1.1.1',
    license: 'MIT',
  },
  {
    name: 'fluent-ffmpeg',
    version: '2.1.3',
    license: 'MIT',
  },
  {
    name: 'fontace',
    version: '0.4.1',
    license: 'MIT',
  },
  {
    name: 'fontkitten',
    version: '1.0.3',
    license: 'MIT',
  },
  {
    name: 'formdata-polyfill',
    version: '4.0.10',
    license: 'MIT',
  },
  {
    name: 'framer-motion',
    version: '12.42.2',
    license: 'MIT',
  },
  {
    name: 'fsevents',
    version: '2.3.3',
    license: 'MIT',
  },
  {
    name: 'gaxios',
    version: '7.2.0',
    license: 'Apache-2.0',
  },
  {
    name: 'gcp-metadata',
    version: '8.1.2',
    license: 'Apache-2.0',
  },
  {
    name: 'get-caller-file',
    version: '2.0.5',
    license: 'ISC',
  },
  {
    name: 'get-east-asian-width',
    version: '1.6.0',
    license: 'MIT',
  },
  {
    name: 'get-tsconfig',
    version: '5.0.0-beta.4',
    license: 'MIT',
  },
  {
    name: 'github-slugger',
    version: '2.0.0',
    license: 'ISC',
  },
  {
    name: 'google-auth-library',
    version: '10.9.0',
    license: 'Apache-2.0',
  },
  {
    name: 'google-logging-utils',
    version: '1.1.3',
    license: 'Apache-2.0',
  },
  {
    name: 'google-logging-utils',
    version: '1.1.4',
    license: 'Apache-2.0',
  },
  {
    name: 'graceful-fs',
    version: '4.2.11',
    license: 'ISC',
  },
  {
    name: 'gsap',
    version: '3.15.0',
    license: "Standard 'no charge' license: https://gsap.com/standard-license.",
  },
  {
    name: 'h3',
    version: '1.15.11',
    license: 'MIT',
  },
  {
    name: 'hachure-fill',
    version: '0.5.2',
    license: 'MIT',
  },
  {
    name: 'hast-util-from-html',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'hast-util-from-parse5',
    version: '8.0.3',
    license: 'MIT',
  },
  {
    name: 'hast-util-parse-selector',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'hast-util-raw',
    version: '9.1.0',
    license: 'MIT',
  },
  {
    name: 'hast-util-sanitize',
    version: '5.0.2',
    license: 'MIT',
  },
  {
    name: 'hast-util-to-html',
    version: '9.0.5',
    license: 'MIT',
  },
  {
    name: 'hast-util-to-jsx-runtime',
    version: '2.3.6',
    license: 'MIT',
  },
  {
    name: 'hast-util-to-parse5',
    version: '8.0.1',
    license: 'MIT',
  },
  {
    name: 'hast-util-whitespace',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'hastscript',
    version: '9.0.1',
    license: 'MIT',
  },
  {
    name: 'hls.js',
    version: '1.6.16',
    license: 'Apache-2.0',
  },
  {
    name: 'hono',
    version: '4.12.30',
    license: 'MIT',
  },
  {
    name: 'hono',
    version: '4.12.34',
    license: 'MIT',
  },
  {
    name: 'html-escaper',
    version: '3.0.3',
    license: 'MIT',
  },
  {
    name: 'html-url-attributes',
    version: '3.0.1',
    license: 'MIT',
  },
  {
    name: 'html-void-elements',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'http-cache-semantics',
    version: '4.2.0',
    license: 'BSD-2-Clause',
  },
  {
    name: 'http-proxy-agent',
    version: '7.0.2',
    license: 'MIT',
  },
  {
    name: 'https-proxy-agent',
    version: '7.0.6',
    license: 'MIT',
  },
  {
    name: 'iconv-lite',
    version: '0.6.3',
    license: 'MIT',
  },
  {
    name: 'ignore',
    version: '7.0.5',
    license: 'MIT',
  },
  {
    name: 'immer',
    version: '11.1.11',
    license: 'MIT',
  },
  {
    name: 'import-meta-resolve',
    version: '2.2.2',
    license: 'MIT',
  },
  {
    name: 'import-meta-resolve',
    version: '4.2.0',
    license: 'MIT',
  },
  {
    name: 'inline-style-parser',
    version: '0.2.7',
    license: 'MIT',
  },
  {
    name: 'internmap',
    version: '1.0.1',
    license: 'ISC',
  },
  {
    name: 'internmap',
    version: '2.0.3',
    license: 'ISC',
  },
  {
    name: 'invariant',
    version: '2.2.4',
    license: 'MIT',
  },
  {
    name: 'iron-webcrypto',
    version: '1.2.1',
    license: 'MIT',
  },
  {
    name: 'is-alphabetical',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'is-alphanumerical',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'is-decimal',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'is-docker',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'is-hexadecimal',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'is-plain-obj',
    version: '4.1.0',
    license: 'MIT',
  },
  {
    name: 'isexe',
    version: '2.0.0',
    license: 'ISC',
  },
  {
    name: 'isexe',
    version: '4.0.0',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'jiti',
    version: '2.7.0',
    license: 'MIT',
  },
  {
    name: 'js-tokens',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'js-yaml',
    version: '4.3.0',
    license: 'MIT',
  },
  {
    name: 'json-bigint',
    version: '1.0.0',
    license: 'MIT',
  },
  {
    name: 'json-schema-to-ts',
    version: '3.1.1',
    license: 'MIT',
  },
  {
    name: 'jsonc-parser',
    version: '3.3.1',
    license: 'MIT',
  },
  {
    name: 'jwa',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'jws',
    version: '4.0.1',
    license: 'MIT',
  },
  {
    name: 'katex',
    version: '0.16.47',
    license: 'MIT',
  },
  {
    name: 'khroma',
    version: '2.1.0',
    license: 'Unknown',
  },
  {
    name: 'layout-base',
    version: '1.0.2',
    license: 'MIT',
  },
  {
    name: 'layout-base',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'lightningcss',
    version: '1.32.0',
    license: 'MPL-2.0',
  },
  {
    name: 'lightningcss-darwin-arm64',
    version: '1.32.0',
    license: 'MPL-2.0',
  },
  {
    name: 'lightweight-charts',
    version: '5.2.0',
    license: 'Apache-2.0',
  },
  {
    name: 'lilconfig',
    version: '3.1.3',
    license: 'MIT',
  },
  {
    name: 'lines-and-columns',
    version: '1.2.4',
    license: 'MIT',
  },
  {
    name: 'lodash-es',
    version: '4.18.1',
    license: 'MIT',
  },
  {
    name: 'long',
    version: '5.3.2',
    license: 'Apache-2.0',
  },
  {
    name: 'longest-streak',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: 'loose-envify',
    version: '1.4.0',
    license: 'MIT',
  },
  {
    name: 'lru-cache',
    version: '11.5.2',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'lucide-react',
    version: '1.25.0',
    license: 'ISC',
  },
  {
    name: 'magic-string',
    version: '0.30.21',
    license: 'MIT',
  },
  {
    name: 'magicast',
    version: '0.5.3',
    license: 'MIT',
  },
  {
    name: 'markdown-table',
    version: '3.0.4',
    license: 'MIT',
  },
  {
    name: 'marked',
    version: '16.4.2',
    license: 'MIT',
  },
  {
    name: 'marked',
    version: '17.0.6',
    license: 'MIT',
  },
  {
    name: 'marked',
    version: '18.0.7',
    license: 'MIT',
  },
  {
    name: 'mathjax-full',
    version: '3.2.2',
    license: 'Apache-2.0',
  },
  {
    name: 'mdast-util-find-and-replace',
    version: '3.0.2',
    license: 'MIT',
  },
  {
    name: 'mdast-util-from-markdown',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm-autolink-literal',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm-footnote',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm-strikethrough',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm-table',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-gfm-task-list-item',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-mdx-expression',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'mdast-util-mdx-jsx',
    version: '3.2.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-mdxjs-esm',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'mdast-util-phrasing',
    version: '4.1.0',
    license: 'MIT',
  },
  {
    name: 'mdast-util-to-hast',
    version: '13.2.1',
    license: 'MIT',
  },
  {
    name: 'mdast-util-to-markdown',
    version: '2.1.2',
    license: 'MIT',
  },
  {
    name: 'mdast-util-to-string',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'mdn-data',
    version: '2.0.28',
    license: 'CC0-1.0',
  },
  {
    name: 'mdn-data',
    version: '2.27.1',
    license: 'CC0-1.0',
  },
  {
    name: 'mermaid',
    version: '11.16.0',
    license: 'MIT',
  },
  {
    name: 'mhchemparser',
    version: '4.2.1',
    license: 'Apache-2.0',
  },
  {
    name: 'micromark',
    version: '4.0.2',
    license: 'MIT',
  },
  {
    name: 'micromark-core-commonmark',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-autolink-literal',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-footnote',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-strikethrough',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-table',
    version: '2.1.1',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-tagfilter',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'micromark-extension-gfm-task-list-item',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'micromark-factory-destination',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-factory-label',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-factory-space',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-factory-title',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-factory-whitespace',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-character',
    version: '2.1.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-chunked',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-classify-character',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-combine-extensions',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-decode-numeric-character-reference',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'micromark-util-decode-string',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-encode',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-html-tag-name',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-normalize-identifier',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-resolve-all',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-sanitize-uri',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-subtokenize',
    version: '2.1.0',
    license: 'MIT',
  },
  {
    name: 'micromark-util-symbol',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'micromark-util-types',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'minipass',
    version: '7.1.3',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'minizlib',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: 'mitt',
    version: '3.0.1',
    license: 'MIT',
  },
  {
    name: 'mj-context-menu',
    version: '0.6.1',
    license: 'Apache-2.0',
  },
  {
    name: 'modern-tar',
    version: '0.7.7',
    license: 'MIT',
  },
  {
    name: 'motion',
    version: '12.42.2',
    license: 'MIT',
  },
  {
    name: 'motion-dom',
    version: '12.42.2',
    license: 'MIT',
  },
  {
    name: 'motion-utils',
    version: '12.39.0',
    license: 'MIT',
  },
  {
    name: 'mp4-wasm',
    version: '1.0.6',
    license: 'MIT',
  },
  {
    name: 'mp4box',
    version: '0.5.4',
    license: 'BSD-3-Clause',
  },
  {
    name: 'mrmime',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'ms',
    version: '2.1.3',
    license: 'MIT',
  },
  {
    name: 'mz',
    version: '2.7.0',
    license: 'MIT',
  },
  {
    name: 'nanoid',
    version: '3.3.16',
    license: 'MIT',
  },
  {
    name: 'neotraverse',
    version: '1.0.1',
    license: 'MIT',
  },
  {
    name: 'nlcst-to-string',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'node-addon-api',
    version: '8.9.0',
    license: 'MIT',
  },
  {
    name: 'node-domexception',
    version: '1.0.0',
    license: 'MIT',
  },
  {
    name: 'node-fetch',
    version: '3.3.2',
    license: 'MIT',
  },
  {
    name: 'node-fetch-native',
    version: '1.6.7',
    license: 'MIT',
  },
  {
    name: 'node-gyp',
    version: '13.0.1',
    license: 'MIT',
  },
  {
    name: 'node-mock-http',
    version: '1.0.4',
    license: 'MIT',
  },
  {
    name: 'nopt',
    version: '10.0.1',
    license: 'ISC',
  },
  {
    name: 'normalize-path',
    version: '3.0.0',
    license: 'MIT',
  },
  {
    name: 'nth-check',
    version: '2.1.1',
    license: 'BSD-2-Clause',
  },
  {
    name: 'object-assign',
    version: '4.1.1',
    license: 'MIT',
  },
  {
    name: 'obug',
    version: '2.1.3',
    license: 'MIT',
  },
  {
    name: 'ofetch',
    version: '1.5.1',
    license: 'MIT',
  },
  {
    name: 'ohash',
    version: '2.0.11',
    license: 'MIT',
  },
  {
    name: 'oniguruma-parser',
    version: '0.12.2',
    license: 'MIT',
  },
  {
    name: 'oniguruma-to-es',
    version: '4.3.6',
    license: 'MIT',
  },
  {
    name: 'openai',
    version: '6.26.0',
    license: 'Apache-2.0',
  },
  {
    name: 'p-limit',
    version: '7.3.0',
    license: 'MIT',
  },
  {
    name: 'p-queue',
    version: '9.3.1',
    license: 'MIT',
  },
  {
    name: 'p-retry',
    version: '4.6.2',
    license: 'MIT',
  },
  {
    name: 'p-timeout',
    version: '7.0.1',
    license: 'MIT',
  },
  {
    name: 'package-manager-detector',
    version: '1.7.0',
    license: 'MIT',
  },
  {
    name: 'parse-entities',
    version: '4.0.2',
    license: 'MIT',
  },
  {
    name: 'parse-svg-path',
    version: '0.2.0',
    license: 'MIT',
  },
  {
    name: 'parse5',
    version: '7.3.0',
    license: 'MIT',
  },
  {
    name: 'partial-json',
    version: '0.1.7',
    license: 'MIT',
  },
  {
    name: 'path-data-parser',
    version: '0.1.0',
    license: 'MIT',
  },
  {
    name: 'piccolore',
    version: '0.1.3',
    license: 'ISC',
  },
  {
    name: 'picocolors',
    version: '1.1.1',
    license: 'ISC',
  },
  {
    name: 'picomatch',
    version: '2.3.2',
    license: 'MIT',
  },
  {
    name: 'picomatch',
    version: '4.0.5',
    license: 'MIT',
  },
  {
    name: 'pirates',
    version: '4.0.7',
    license: 'MIT',
  },
  {
    name: 'points-on-curve',
    version: '0.2.0',
    license: 'MIT',
  },
  {
    name: 'points-on-path',
    version: '0.2.1',
    license: 'MIT',
  },
  {
    name: 'postcss',
    version: '8.5.19',
    license: 'MIT',
  },
  {
    name: 'posthog-node',
    version: '5.46.1',
    license: 'MIT',
  },
  {
    name: 'prismjs',
    version: '1.30.0',
    license: 'MIT',
  },
  {
    name: 'proc-log',
    version: '7.0.0',
    license: 'ISC',
  },
  {
    name: 'process-ancestry',
    version: '0.1.0',
    license: 'MIT',
  },
  {
    name: 'progress',
    version: '2.0.3',
    license: 'MIT',
  },
  {
    name: 'property-information',
    version: '7.2.0',
    license: 'MIT',
  },
  {
    name: 'protobufjs',
    version: '7.6.5',
    license: 'BSD-3-Clause',
  },
  {
    name: 'puppeteer',
    version: '25.4.0',
    license: 'Apache-2.0',
  },
  {
    name: 'puppeteer-core',
    version: '25.4.0',
    license: 'Apache-2.0',
  },
  {
    name: 'quickjs-emscripten',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: 'quickjs-emscripten-core',
    version: '0.32.0',
    license: 'MIT',
  },
  {
    name: 'radix3',
    version: '1.1.2',
    license: 'MIT',
  },
  {
    name: 'react',
    version: '19.2.7',
    license: 'MIT',
  },
  {
    name: 'react-dom',
    version: '19.2.7',
    license: 'MIT',
  },
  {
    name: 'react-is',
    version: '19.2.7',
    license: 'MIT',
  },
  {
    name: 'react-redux',
    version: '9.3.0',
    license: 'MIT',
  },
  {
    name: 'react-router',
    version: '8.3.0',
    license: 'MIT',
  },
  {
    name: 'readdirp',
    version: '5.0.0',
    license: 'MIT',
  },
  {
    name: 'recharts',
    version: '3.9.2',
    license: 'MIT',
  },
  {
    name: 'redux',
    version: '5.0.1',
    license: 'MIT',
  },
  {
    name: 'redux-thunk',
    version: '3.1.0',
    license: 'MIT',
  },
  {
    name: 'reflect-metadata',
    version: '0.2.2',
    license: 'Apache-2.0',
  },
  {
    name: 'regex',
    version: '6.1.0',
    license: 'MIT',
  },
  {
    name: 'regex-recursion',
    version: '6.0.2',
    license: 'MIT',
  },
  {
    name: 'regex-utilities',
    version: '2.3.0',
    license: 'MIT',
  },
  {
    name: 'rehype-harden',
    version: '1.1.8',
    license: 'MIT',
  },
  {
    name: 'rehype-raw',
    version: '7.0.0',
    license: 'MIT',
  },
  {
    name: 'rehype-sanitize',
    version: '6.0.0',
    license: 'MIT',
  },
  {
    name: 'remark-gfm',
    version: '4.0.1',
    license: 'MIT',
  },
  {
    name: 'remark-parse',
    version: '11.0.0',
    license: 'MIT',
  },
  {
    name: 'remark-rehype',
    version: '11.1.2',
    license: 'MIT',
  },
  {
    name: 'remark-stringify',
    version: '11.0.0',
    license: 'MIT',
  },
  {
    name: 'remend',
    version: '1.3.0',
    license: 'Apache-2.0',
  },
  {
    name: 'reselect',
    version: '5.2.0',
    license: 'MIT',
  },
  {
    name: 'resolve-pkg-maps',
    version: '1.0.0',
    license: 'MIT',
  },
  {
    name: 'retext-smartypants',
    version: '6.2.0',
    license: 'MIT',
  },
  {
    name: 'retry',
    version: '0.13.1',
    license: 'MIT',
  },
  {
    name: 'robust-predicates',
    version: '3.0.3',
    license: 'Unlicense',
  },
  {
    name: 'rolldown',
    version: '1.1.5',
    license: 'MIT',
  },
  {
    name: 'rollup',
    version: '3.30.0',
    license: 'MIT',
  },
  {
    name: 'roughjs',
    version: '4.6.6',
    license: 'MIT',
  },
  {
    name: 'rw',
    version: '1.3.3',
    license: 'BSD-3-Clause',
  },
  {
    name: 'rxjs',
    version: '7.8.2',
    license: 'Apache-2.0',
  },
  {
    name: 'safe-buffer',
    version: '5.2.1',
    license: 'MIT',
  },
  {
    name: 'safer-buffer',
    version: '2.1.2',
    license: 'MIT',
  },
  {
    name: 'satteri',
    version: '0.9.5',
    license: 'MIT',
  },
  {
    name: 'sax',
    version: '1.6.0',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'scheduler',
    version: '0.27.0',
    license: 'MIT',
  },
  {
    name: 'semver',
    version: '7.8.5',
    license: 'ISC',
  },
  {
    name: 'sharp',
    version: '0.35.3',
    license: 'Apache-2.0',
  },
  {
    name: 'shiki',
    version: '4.3.1',
    license: 'MIT',
  },
  {
    name: 'sisteransi',
    version: '1.0.5',
    license: 'MIT',
  },
  {
    name: 'sitemap',
    version: '9.0.1',
    license: 'MIT',
  },
  {
    name: 'smol-toml',
    version: '1.7.0',
    license: 'BSD-3-Clause',
  },
  {
    name: 'source-map-js',
    version: '1.2.1',
    license: 'BSD-3-Clause',
  },
  {
    name: 'space-separated-tokens',
    version: '2.0.2',
    license: 'MIT',
  },
  {
    name: 'speech-rule-engine',
    version: '4.1.4',
    license: 'Apache-2.0',
  },
  {
    name: 'stream-replace-string',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'streamdown',
    version: '2.5.0',
    license: 'Apache-2.0',
  },
  {
    name: 'string-width',
    version: '7.2.0',
    license: 'MIT',
  },
  {
    name: 'stringify-entities',
    version: '4.0.4',
    license: 'MIT',
  },
  {
    name: 'strip-ansi',
    version: '7.2.0',
    license: 'MIT',
  },
  {
    name: 'style-mod',
    version: '4.1.3',
    license: 'MIT',
  },
  {
    name: 'style-to-js',
    version: '1.1.21',
    license: 'MIT',
  },
  {
    name: 'style-to-object',
    version: '1.0.14',
    license: 'MIT',
  },
  {
    name: 'styleq',
    version: '0.2.1',
    license: 'MIT',
  },
  {
    name: 'stylis',
    version: '4.4.0',
    license: 'MIT',
  },
  {
    name: 'sucrase',
    version: '3.35.1',
    license: 'MIT',
  },
  {
    name: 'sumchecker',
    version: '3.0.1',
    license: 'Apache-2.0',
  },
  {
    name: 'svgo',
    version: '4.0.2',
    license: 'MIT',
  },
  {
    name: 'tailwind-merge',
    version: '3.6.0',
    license: 'MIT',
  },
  {
    name: 'tar',
    version: '7.5.20',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'thenify',
    version: '3.3.1',
    license: 'MIT',
  },
  {
    name: 'thenify-all',
    version: '1.6.0',
    license: 'MIT',
  },
  {
    name: 'three',
    version: '0.185.1',
    license: 'MIT',
  },
  {
    name: 'tiny-inflate',
    version: '1.0.3',
    license: 'MIT',
  },
  {
    name: 'tiny-invariant',
    version: '1.3.3',
    license: 'MIT',
  },
  {
    name: 'tinyclip',
    version: '0.1.15',
    license: 'MIT',
  },
  {
    name: 'tinyexec',
    version: '1.2.4',
    license: 'MIT',
  },
  {
    name: 'tinyglobby',
    version: '0.2.17',
    license: 'MIT',
  },
  {
    name: 'trim-lines',
    version: '3.0.1',
    license: 'MIT',
  },
  {
    name: 'trough',
    version: '2.2.0',
    license: 'MIT',
  },
  {
    name: 'ts-algebra',
    version: '2.0.0',
    license: 'MIT',
  },
  {
    name: 'ts-dedent',
    version: '2.3.0',
    license: 'MIT',
  },
  {
    name: 'ts-interface-checker',
    version: '0.1.13',
    license: 'Apache-2.0',
  },
  {
    name: 'tslib',
    version: '1.14.1',
    license: '0BSD',
  },
  {
    name: 'tslib',
    version: '2.8.1',
    license: '0BSD',
  },
  {
    name: 'tsx',
    version: '4.23.1',
    license: 'MIT',
  },
  {
    name: 'tsyringe',
    version: '4.10.0',
    license: 'MIT',
  },
  {
    name: 'typebox',
    version: '1.3.6',
    license: 'MIT',
  },
  {
    name: 'typebox',
    version: '1.3.7',
    license: 'MIT',
  },
  {
    name: 'typed-query-selector',
    version: '2.12.2',
    license: 'MIT',
  },
  {
    name: 'ufo',
    version: '1.6.4',
    license: 'MIT',
  },
  {
    name: 'ultrahtml',
    version: '1.7.0',
    license: 'MIT',
  },
  {
    name: 'uncrypto',
    version: '0.1.3',
    license: 'MIT',
  },
  {
    name: 'undici',
    version: '7.28.0',
    license: 'MIT',
  },
  {
    name: 'undici',
    version: '8.7.0',
    license: 'MIT',
  },
  {
    name: 'undici-types',
    version: '7.18.2',
    license: 'MIT',
  },
  {
    name: 'undici-types',
    version: '8.3.0',
    license: 'MIT',
  },
  {
    name: 'unified',
    version: '11.0.5',
    license: 'MIT',
  },
  {
    name: 'unifont',
    version: '0.7.4',
    license: 'MIT',
  },
  {
    name: 'unist-util-is',
    version: '6.0.1',
    license: 'MIT',
  },
  {
    name: 'unist-util-position',
    version: '5.0.0',
    license: 'MIT',
  },
  {
    name: 'unist-util-stringify-position',
    version: '4.0.0',
    license: 'MIT',
  },
  {
    name: 'unist-util-visit',
    version: '5.1.0',
    license: 'MIT',
  },
  {
    name: 'unist-util-visit-parents',
    version: '6.0.2',
    license: 'MIT',
  },
  {
    name: 'unstorage',
    version: '1.17.5',
    license: 'MIT',
  },
  {
    name: 'use-sync-external-store',
    version: '1.6.0',
    license: 'MIT',
  },
  {
    name: 'uuid',
    version: '14.0.1',
    license: 'MIT',
  },
  {
    name: 'vfile',
    version: '6.0.3',
    license: 'MIT',
  },
  {
    name: 'vfile-location',
    version: '5.0.3',
    license: 'MIT',
  },
  {
    name: 'vfile-message',
    version: '4.0.3',
    license: 'MIT',
  },
  {
    name: 'victory-vendor',
    version: '37.3.6',
    license: 'MIT AND ISC',
  },
  {
    name: 'vite',
    version: '8.1.5',
    license: 'MIT',
  },
  {
    name: 'vitefu',
    version: '1.1.3',
    license: 'MIT',
  },
  {
    name: 'vscode-oniguruma',
    version: '1.7.0',
    license: 'MIT',
  },
  {
    name: 'vscode-textmate',
    version: '9.3.2',
    license: 'MIT',
  },
  {
    name: 'w3c-keyname',
    version: '2.2.8',
    license: 'MIT',
  },
  {
    name: 'web-namespaces',
    version: '2.0.1',
    license: 'MIT',
  },
  {
    name: 'web-streams-polyfill',
    version: '3.3.3',
    license: 'MIT',
  },
  {
    name: 'webdriver-bidi-protocol',
    version: '0.4.2',
    license: 'Apache-2.0',
  },
  {
    name: 'which',
    version: '1.3.1',
    license: 'ISC',
  },
  {
    name: 'which',
    version: '7.0.0',
    license: 'ISC',
  },
  {
    name: 'wicked-good-xpath',
    version: '1.3.0',
    license: 'MIT',
  },
  {
    name: 'wrap-ansi',
    version: '9.0.2',
    license: 'MIT',
  },
  {
    name: 'ws',
    version: '8.21.1',
    license: 'MIT',
  },
  {
    name: 'xxhash-wasm',
    version: '1.1.0',
    license: 'MIT',
  },
  {
    name: 'y18n',
    version: '5.0.8',
    license: 'ISC',
  },
  {
    name: 'yallist',
    version: '5.0.0',
    license: 'BlueOak-1.0.0',
  },
  {
    name: 'yaml',
    version: '2.9.0',
    license: 'ISC',
  },
  {
    name: 'yargs',
    version: '18.0.0',
    license: 'MIT',
  },
  {
    name: 'yargs-parser',
    version: '22.0.0',
    license: 'ISC',
  },
  {
    name: 'yocto-queue',
    version: '1.2.2',
    license: 'MIT',
  },
  {
    name: 'zod',
    version: '3.25.76',
    license: 'MIT',
  },
  {
    name: 'zod',
    version: '4.4.3',
    license: 'MIT',
  },
  {
    name: 'zod-to-json-schema',
    version: '3.25.2',
    license: 'ISC',
  },
  {
    name: 'zwitch',
    version: '2.0.4',
    license: 'MIT',
  },
];
