// Generated by scripts/generate-credits.mjs — do not edit. Refresh with `pnpm credits`.
export type CreditEntry = { name: string; version: string; license: string };

export const CREDITS: CreditEntry[] = [
  {
    "name": "@antfu/install-pkg",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "@anthropic-ai/sdk",
    "version": "0.91.1",
    "license": "MIT"
  },
  {
    "name": "@aws-crypto/sha256-browser",
    "version": "5.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-crypto/sha256-js",
    "version": "5.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-crypto/supports-web-crypto",
    "version": "5.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-crypto/util",
    "version": "5.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/client-bedrock-runtime",
    "version": "3.1048.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/core",
    "version": "3.975.2",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-env",
    "version": "3.972.58",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-http",
    "version": "3.972.60",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-ini",
    "version": "3.973.2",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-login",
    "version": "3.972.64",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-node",
    "version": "3.972.68",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-process",
    "version": "3.972.58",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-sso",
    "version": "3.973.2",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/credential-provider-web-identity",
    "version": "3.972.64",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/eventstream-handler-node",
    "version": "3.972.27",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/middleware-eventstream",
    "version": "3.972.23",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/middleware-websocket",
    "version": "3.972.40",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/nested-clients",
    "version": "3.997.32",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/signature-v4-multi-region",
    "version": "3.996.40",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/token-providers",
    "version": "3.1048.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/token-providers",
    "version": "3.1087.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/types",
    "version": "3.974.1",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/util-locate-window",
    "version": "3.965.8",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws-sdk/xml-builder",
    "version": "3.972.35",
    "license": "Apache-2.0"
  },
  {
    "name": "@aws/lambda-invoke-store",
    "version": "0.3.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@babel/runtime",
    "version": "7.29.7",
    "license": "MIT"
  },
  {
    "name": "@base-ui/react",
    "version": "1.6.0",
    "license": "MIT"
  },
  {
    "name": "@base-ui/utils",
    "version": "0.3.1",
    "license": "MIT"
  },
  {
    "name": "@braintree/sanitize-url",
    "version": "7.1.2",
    "license": "MIT"
  },
  {
    "name": "@chevrotain/types",
    "version": "11.1.2",
    "license": "Apache-2.0"
  },
  {
    "name": "@earendil-works/pi-agent-core",
    "version": "0.80.7",
    "license": "MIT"
  },
  {
    "name": "@earendil-works/pi-ai",
    "version": "0.80.7",
    "license": "MIT"
  },
  {
    "name": "@electron-internal/extract-zip",
    "version": "1.0.4",
    "license": "BSD-2-Clause"
  },
  {
    "name": "@electron/get",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "@floating-ui/core",
    "version": "1.8.0",
    "license": "MIT"
  },
  {
    "name": "@floating-ui/dom",
    "version": "1.8.0",
    "license": "MIT"
  },
  {
    "name": "@floating-ui/react-dom",
    "version": "2.1.9",
    "license": "MIT"
  },
  {
    "name": "@floating-ui/utils",
    "version": "0.2.12",
    "license": "MIT"
  },
  {
    "name": "@google/genai",
    "version": "1.52.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@hono/node-server",
    "version": "2.0.9",
    "license": "MIT"
  },
  {
    "name": "@iconify/types",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "@iconify/utils",
    "version": "3.1.4",
    "license": "MIT"
  },
  {
    "name": "@mermaid-js/parser",
    "version": "1.2.0",
    "license": "MIT"
  },
  {
    "name": "@mistralai/mistralai",
    "version": "2.2.6",
    "license": "Apache-2.0"
  },
  {
    "name": "@opentelemetry/api",
    "version": "1.9.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@opentelemetry/semantic-conventions",
    "version": "1.43.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@protobufjs/aspromise",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/base64",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/codegen",
    "version": "2.0.5",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/eventemitter",
    "version": "1.1.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/fetch",
    "version": "1.1.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/float",
    "version": "1.0.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/path",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/pool",
    "version": "1.1.0",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/utf8",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@reduxjs/toolkit",
    "version": "2.12.0",
    "license": "MIT"
  },
  {
    "name": "@smithy/core",
    "version": "3.29.4",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/credential-provider-imds",
    "version": "4.4.9",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/fetch-http-handler",
    "version": "5.6.6",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/is-array-buffer",
    "version": "2.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/node-http-handler",
    "version": "4.7.3",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/node-http-handler",
    "version": "4.9.6",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/signature-v4",
    "version": "5.6.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/types",
    "version": "4.16.1",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/util-buffer-from",
    "version": "2.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@smithy/util-utf8",
    "version": "2.3.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@standard-schema/spec",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "@standard-schema/utils",
    "version": "0.3.0",
    "license": "MIT"
  },
  {
    "name": "@tanstack/query-core",
    "version": "5.101.2",
    "license": "MIT"
  },
  {
    "name": "@tanstack/query-persist-client-core",
    "version": "5.101.2",
    "license": "MIT"
  },
  {
    "name": "@tanstack/query-sync-storage-persister",
    "version": "5.101.2",
    "license": "MIT"
  },
  {
    "name": "@tanstack/react-query",
    "version": "5.101.2",
    "license": "MIT"
  },
  {
    "name": "@tanstack/react-query-persist-client",
    "version": "5.101.2",
    "license": "MIT"
  },
  {
    "name": "@tsuki-hono/common",
    "version": "0.0.5",
    "license": "MIT"
  },
  {
    "name": "@tsuki-hono/core",
    "version": "0.0.5",
    "license": "MIT"
  },
  {
    "name": "@types/better-sqlite3",
    "version": "7.6.13",
    "license": "MIT"
  },
  {
    "name": "@types/d3",
    "version": "7.4.3",
    "license": "MIT"
  },
  {
    "name": "@types/d3-array",
    "version": "3.2.2",
    "license": "MIT"
  },
  {
    "name": "@types/d3-axis",
    "version": "3.0.6",
    "license": "MIT"
  },
  {
    "name": "@types/d3-brush",
    "version": "3.0.6",
    "license": "MIT"
  },
  {
    "name": "@types/d3-chord",
    "version": "3.0.6",
    "license": "MIT"
  },
  {
    "name": "@types/d3-color",
    "version": "3.1.3",
    "license": "MIT"
  },
  {
    "name": "@types/d3-contour",
    "version": "3.0.6",
    "license": "MIT"
  },
  {
    "name": "@types/d3-delaunay",
    "version": "6.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/d3-dispatch",
    "version": "3.0.7",
    "license": "MIT"
  },
  {
    "name": "@types/d3-drag",
    "version": "3.0.7",
    "license": "MIT"
  },
  {
    "name": "@types/d3-dsv",
    "version": "3.0.7",
    "license": "MIT"
  },
  {
    "name": "@types/d3-ease",
    "version": "3.0.2",
    "license": "MIT"
  },
  {
    "name": "@types/d3-fetch",
    "version": "3.0.7",
    "license": "MIT"
  },
  {
    "name": "@types/d3-force",
    "version": "3.0.10",
    "license": "MIT"
  },
  {
    "name": "@types/d3-format",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/d3-geo",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "@types/d3-hierarchy",
    "version": "3.1.7",
    "license": "MIT"
  },
  {
    "name": "@types/d3-interpolate",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/d3-path",
    "version": "3.1.1",
    "license": "MIT"
  },
  {
    "name": "@types/d3-polygon",
    "version": "3.0.2",
    "license": "MIT"
  },
  {
    "name": "@types/d3-quadtree",
    "version": "3.0.6",
    "license": "MIT"
  },
  {
    "name": "@types/d3-random",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/d3-scale",
    "version": "4.0.9",
    "license": "MIT"
  },
  {
    "name": "@types/d3-scale-chromatic",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "@types/d3-selection",
    "version": "3.0.11",
    "license": "MIT"
  },
  {
    "name": "@types/d3-shape",
    "version": "3.1.8",
    "license": "MIT"
  },
  {
    "name": "@types/d3-time",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/d3-time-format",
    "version": "4.0.3",
    "license": "MIT"
  },
  {
    "name": "@types/d3-timer",
    "version": "3.0.2",
    "license": "MIT"
  },
  {
    "name": "@types/d3-transition",
    "version": "3.0.9",
    "license": "MIT"
  },
  {
    "name": "@types/d3-zoom",
    "version": "3.0.8",
    "license": "MIT"
  },
  {
    "name": "@types/debug",
    "version": "4.1.13",
    "license": "MIT"
  },
  {
    "name": "@types/estree",
    "version": "1.0.9",
    "license": "MIT"
  },
  {
    "name": "@types/estree-jsx",
    "version": "1.0.5",
    "license": "MIT"
  },
  {
    "name": "@types/geojson",
    "version": "7946.0.16",
    "license": "MIT"
  },
  {
    "name": "@types/hast",
    "version": "3.0.5",
    "license": "MIT"
  },
  {
    "name": "@types/mdast",
    "version": "4.0.4",
    "license": "MIT"
  },
  {
    "name": "@types/ms",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "@types/node",
    "version": "24.13.3",
    "license": "MIT"
  },
  {
    "name": "@types/node",
    "version": "26.1.1",
    "license": "MIT"
  },
  {
    "name": "@types/react",
    "version": "19.2.17",
    "license": "MIT"
  },
  {
    "name": "@types/retry",
    "version": "0.12.0",
    "license": "MIT"
  },
  {
    "name": "@types/trusted-types",
    "version": "2.0.7",
    "license": "MIT"
  },
  {
    "name": "@types/unist",
    "version": "2.0.11",
    "license": "MIT"
  },
  {
    "name": "@types/unist",
    "version": "3.0.3",
    "license": "MIT"
  },
  {
    "name": "@types/use-sync-external-store",
    "version": "0.0.6",
    "license": "MIT"
  },
  {
    "name": "@ungap/structured-clone",
    "version": "1.3.3",
    "license": "ISC"
  },
  {
    "name": "@upsetjs/venn.js",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "agent-base",
    "version": "7.1.4",
    "license": "MIT"
  },
  {
    "name": "ansi-regex",
    "version": "6.2.2",
    "license": "MIT"
  },
  {
    "name": "ansi-styles",
    "version": "6.2.3",
    "license": "MIT"
  },
  {
    "name": "bail",
    "version": "2.0.2",
    "license": "MIT"
  },
  {
    "name": "base64-js",
    "version": "1.5.1",
    "license": "MIT"
  },
  {
    "name": "better-sqlite3",
    "version": "12.11.1",
    "license": "MIT"
  },
  {
    "name": "bignumber.js",
    "version": "9.3.1",
    "license": "MIT"
  },
  {
    "name": "bindings",
    "version": "1.5.0",
    "license": "MIT"
  },
  {
    "name": "bl",
    "version": "4.1.0",
    "license": "MIT"
  },
  {
    "name": "bowser",
    "version": "2.14.1",
    "license": "MIT"
  },
  {
    "name": "buffer",
    "version": "5.7.1",
    "license": "MIT"
  },
  {
    "name": "buffer-equal-constant-time",
    "version": "1.0.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "ccount",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "character-entities",
    "version": "2.0.2",
    "license": "MIT"
  },
  {
    "name": "character-entities-html4",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "character-entities-legacy",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "character-reference-invalid",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "chownr",
    "version": "1.1.4",
    "license": "ISC"
  },
  {
    "name": "cli-truncate",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "clsx",
    "version": "2.1.1",
    "license": "MIT"
  },
  {
    "name": "comma-separated-tokens",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "commander",
    "version": "7.2.0",
    "license": "MIT"
  },
  {
    "name": "commander",
    "version": "8.3.0",
    "license": "MIT"
  },
  {
    "name": "cose-base",
    "version": "1.0.3",
    "license": "MIT"
  },
  {
    "name": "cose-base",
    "version": "2.2.0",
    "license": "MIT"
  },
  {
    "name": "csstype",
    "version": "3.2.3",
    "license": "MIT"
  },
  {
    "name": "cytoscape",
    "version": "3.34.0",
    "license": "MIT"
  },
  {
    "name": "cytoscape-cose-bilkent",
    "version": "4.1.0",
    "license": "MIT"
  },
  {
    "name": "cytoscape-fcose",
    "version": "2.2.0",
    "license": "MIT"
  },
  {
    "name": "d3",
    "version": "7.9.0",
    "license": "ISC"
  },
  {
    "name": "d3-array",
    "version": "2.12.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "d3-array",
    "version": "3.2.4",
    "license": "ISC"
  },
  {
    "name": "d3-axis",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "d3-brush",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "d3-chord",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-color",
    "version": "3.1.0",
    "license": "ISC"
  },
  {
    "name": "d3-contour",
    "version": "4.0.2",
    "license": "ISC"
  },
  {
    "name": "d3-delaunay",
    "version": "6.0.4",
    "license": "ISC"
  },
  {
    "name": "d3-dispatch",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-drag",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "d3-dsv",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-ease",
    "version": "3.0.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "d3-fetch",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-force",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "d3-format",
    "version": "3.1.2",
    "license": "ISC"
  },
  {
    "name": "d3-geo",
    "version": "3.1.1",
    "license": "ISC"
  },
  {
    "name": "d3-hierarchy",
    "version": "3.1.2",
    "license": "ISC"
  },
  {
    "name": "d3-interpolate",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-path",
    "version": "1.0.9",
    "license": "BSD-3-Clause"
  },
  {
    "name": "d3-path",
    "version": "3.1.0",
    "license": "ISC"
  },
  {
    "name": "d3-polygon",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-quadtree",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-random",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-sankey",
    "version": "0.12.3",
    "license": "BSD-3-Clause"
  },
  {
    "name": "d3-scale",
    "version": "4.0.2",
    "license": "ISC"
  },
  {
    "name": "d3-scale-chromatic",
    "version": "3.1.0",
    "license": "ISC"
  },
  {
    "name": "d3-selection",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "d3-shape",
    "version": "1.3.7",
    "license": "BSD-3-Clause"
  },
  {
    "name": "d3-shape",
    "version": "3.2.0",
    "license": "ISC"
  },
  {
    "name": "d3-time",
    "version": "3.1.0",
    "license": "ISC"
  },
  {
    "name": "d3-time-format",
    "version": "4.1.0",
    "license": "ISC"
  },
  {
    "name": "d3-timer",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-transition",
    "version": "3.0.1",
    "license": "ISC"
  },
  {
    "name": "d3-zoom",
    "version": "3.0.0",
    "license": "ISC"
  },
  {
    "name": "dagre-d3-es",
    "version": "7.0.14",
    "license": "MIT"
  },
  {
    "name": "data-uri-to-buffer",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "dayjs",
    "version": "1.11.21",
    "license": "MIT"
  },
  {
    "name": "debug",
    "version": "4.4.3",
    "license": "MIT"
  },
  {
    "name": "decimal.js-light",
    "version": "2.5.1",
    "license": "MIT"
  },
  {
    "name": "decode-named-character-reference",
    "version": "1.3.0",
    "license": "MIT"
  },
  {
    "name": "decompress-response",
    "version": "6.0.0",
    "license": "MIT"
  },
  {
    "name": "deep-extend",
    "version": "0.6.0",
    "license": "MIT"
  },
  {
    "name": "delaunator",
    "version": "5.1.0",
    "license": "ISC"
  },
  {
    "name": "dequal",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "detect-libc",
    "version": "2.1.2",
    "license": "Apache-2.0"
  },
  {
    "name": "devlop",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "dompurify",
    "version": "3.4.12",
    "license": "(MPL-2.0 OR Apache-2.0)"
  },
  {
    "name": "drizzle-orm",
    "version": "0.45.2",
    "license": "Apache-2.0"
  },
  {
    "name": "ecdsa-sig-formatter",
    "version": "1.0.11",
    "license": "Apache-2.0"
  },
  {
    "name": "electron",
    "version": "43.1.1",
    "license": "MIT"
  },
  {
    "name": "electron-context-menu",
    "version": "4.1.2",
    "license": "MIT"
  },
  {
    "name": "electron-dl",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "electron-ipc-decorator",
    "version": "1.0.1",
    "license": "MIT"
  },
  {
    "name": "electron-is-dev",
    "version": "3.0.1",
    "license": "MIT"
  },
  {
    "name": "electron-window-state",
    "version": "5.0.3",
    "license": "MIT"
  },
  {
    "name": "emoji-regex",
    "version": "10.6.0",
    "license": "MIT"
  },
  {
    "name": "end-of-stream",
    "version": "1.4.5",
    "license": "MIT"
  },
  {
    "name": "entities",
    "version": "6.0.1",
    "license": "BSD-2-Clause"
  },
  {
    "name": "env-paths",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "es-toolkit",
    "version": "1.49.0",
    "license": "MIT"
  },
  {
    "name": "escape-goat",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "escape-string-regexp",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "estree-util-is-identifier-name",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "eventemitter3",
    "version": "5.0.4",
    "license": "MIT"
  },
  {
    "name": "expand-template",
    "version": "2.0.3",
    "license": "(MIT OR WTFPL)"
  },
  {
    "name": "ext-list",
    "version": "2.2.2",
    "license": "MIT"
  },
  {
    "name": "ext-name",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "extend",
    "version": "3.0.2",
    "license": "MIT"
  },
  {
    "name": "fancy-canvas",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "fetch-blob",
    "version": "3.2.0",
    "license": "MIT"
  },
  {
    "name": "file-uri-to-path",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "formdata-polyfill",
    "version": "4.0.10",
    "license": "MIT"
  },
  {
    "name": "framer-motion",
    "version": "12.42.2",
    "license": "MIT"
  },
  {
    "name": "fs-constants",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "gaxios",
    "version": "7.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "gcp-metadata",
    "version": "8.1.2",
    "license": "Apache-2.0"
  },
  {
    "name": "get-east-asian-width",
    "version": "1.6.0",
    "license": "MIT"
  },
  {
    "name": "github-from-package",
    "version": "0.0.0",
    "license": "MIT"
  },
  {
    "name": "google-auth-library",
    "version": "10.9.0",
    "license": "Apache-2.0"
  },
  {
    "name": "google-logging-utils",
    "version": "1.1.3",
    "license": "Apache-2.0"
  },
  {
    "name": "google-logging-utils",
    "version": "1.1.4",
    "license": "Apache-2.0"
  },
  {
    "name": "graceful-fs",
    "version": "4.2.11",
    "license": "ISC"
  },
  {
    "name": "gsap",
    "version": "3.15.0",
    "license": "Standard 'no charge' license: https://gsap.com/standard-license."
  },
  {
    "name": "hachure-fill",
    "version": "0.5.2",
    "license": "MIT"
  },
  {
    "name": "hast-util-from-parse5",
    "version": "8.0.3",
    "license": "MIT"
  },
  {
    "name": "hast-util-parse-selector",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "hast-util-raw",
    "version": "9.1.0",
    "license": "MIT"
  },
  {
    "name": "hast-util-sanitize",
    "version": "5.0.2",
    "license": "MIT"
  },
  {
    "name": "hast-util-to-jsx-runtime",
    "version": "2.3.6",
    "license": "MIT"
  },
  {
    "name": "hast-util-to-parse5",
    "version": "8.0.1",
    "license": "MIT"
  },
  {
    "name": "hast-util-whitespace",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "hastscript",
    "version": "9.0.1",
    "license": "MIT"
  },
  {
    "name": "hono",
    "version": "4.12.30",
    "license": "MIT"
  },
  {
    "name": "html-url-attributes",
    "version": "3.0.1",
    "license": "MIT"
  },
  {
    "name": "html-void-elements",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "http-proxy-agent",
    "version": "7.0.2",
    "license": "MIT"
  },
  {
    "name": "https-proxy-agent",
    "version": "7.0.6",
    "license": "MIT"
  },
  {
    "name": "iconv-lite",
    "version": "0.6.3",
    "license": "MIT"
  },
  {
    "name": "ieee754",
    "version": "1.2.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "ignore",
    "version": "7.0.5",
    "license": "MIT"
  },
  {
    "name": "immer",
    "version": "11.1.11",
    "license": "MIT"
  },
  {
    "name": "import-meta-resolve",
    "version": "4.2.0",
    "license": "MIT"
  },
  {
    "name": "inherits",
    "version": "2.0.4",
    "license": "ISC"
  },
  {
    "name": "ini",
    "version": "1.3.8",
    "license": "ISC"
  },
  {
    "name": "inline-style-parser",
    "version": "0.2.7",
    "license": "MIT"
  },
  {
    "name": "internmap",
    "version": "1.0.1",
    "license": "ISC"
  },
  {
    "name": "internmap",
    "version": "2.0.3",
    "license": "ISC"
  },
  {
    "name": "is-alphabetical",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "is-alphanumerical",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "is-decimal",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "is-fullwidth-code-point",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "is-hexadecimal",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "is-plain-obj",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "is-plain-obj",
    "version": "4.1.0",
    "license": "MIT"
  },
  {
    "name": "json-bigint",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "json-schema-to-ts",
    "version": "3.1.1",
    "license": "MIT"
  },
  {
    "name": "jsonfile",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "jwa",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "jws",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "katex",
    "version": "0.16.47",
    "license": "MIT"
  },
  {
    "name": "khroma",
    "version": "2.1.0",
    "license": "Unknown"
  },
  {
    "name": "layout-base",
    "version": "1.0.2",
    "license": "MIT"
  },
  {
    "name": "layout-base",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "lightweight-charts",
    "version": "5.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "lodash-es",
    "version": "4.18.1",
    "license": "MIT"
  },
  {
    "name": "long",
    "version": "5.3.2",
    "license": "Apache-2.0"
  },
  {
    "name": "longest-streak",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "lucide-react",
    "version": "1.24.0",
    "license": "ISC"
  },
  {
    "name": "markdown-table",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "marked",
    "version": "16.4.2",
    "license": "MIT"
  },
  {
    "name": "marked",
    "version": "17.0.6",
    "license": "MIT"
  },
  {
    "name": "mdast-util-find-and-replace",
    "version": "3.0.2",
    "license": "MIT"
  },
  {
    "name": "mdast-util-from-markdown",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm-autolink-literal",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm-footnote",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm-strikethrough",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm-table",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-gfm-task-list-item",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-mdx-expression",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "mdast-util-mdx-jsx",
    "version": "3.2.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-mdxjs-esm",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "mdast-util-phrasing",
    "version": "4.1.0",
    "license": "MIT"
  },
  {
    "name": "mdast-util-to-hast",
    "version": "13.2.1",
    "license": "MIT"
  },
  {
    "name": "mdast-util-to-markdown",
    "version": "2.1.2",
    "license": "MIT"
  },
  {
    "name": "mdast-util-to-string",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "mermaid",
    "version": "11.16.0",
    "license": "MIT"
  },
  {
    "name": "micromark",
    "version": "4.0.2",
    "license": "MIT"
  },
  {
    "name": "micromark-core-commonmark",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-autolink-literal",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-footnote",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-strikethrough",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-table",
    "version": "2.1.1",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-tagfilter",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "micromark-extension-gfm-task-list-item",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "micromark-factory-destination",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-factory-label",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-factory-space",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-factory-title",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-factory-whitespace",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-character",
    "version": "2.1.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-chunked",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-classify-character",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-combine-extensions",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-decode-numeric-character-reference",
    "version": "2.0.2",
    "license": "MIT"
  },
  {
    "name": "micromark-util-decode-string",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-encode",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-html-tag-name",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-normalize-identifier",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-resolve-all",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-sanitize-uri",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-subtokenize",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "micromark-util-symbol",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "micromark-util-types",
    "version": "2.0.2",
    "license": "MIT"
  },
  {
    "name": "mime-db",
    "version": "1.54.0",
    "license": "MIT"
  },
  {
    "name": "mimic-response",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "minimist",
    "version": "1.2.8",
    "license": "MIT"
  },
  {
    "name": "mkdirp",
    "version": "0.5.6",
    "license": "MIT"
  },
  {
    "name": "mkdirp-classic",
    "version": "0.5.3",
    "license": "MIT"
  },
  {
    "name": "motion",
    "version": "12.42.2",
    "license": "MIT"
  },
  {
    "name": "motion-dom",
    "version": "12.42.2",
    "license": "MIT"
  },
  {
    "name": "motion-utils",
    "version": "12.39.0",
    "license": "MIT"
  },
  {
    "name": "ms",
    "version": "2.1.3",
    "license": "MIT"
  },
  {
    "name": "napi-build-utils",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "node-abi",
    "version": "3.94.0",
    "license": "MIT"
  },
  {
    "name": "node-domexception",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "node-fetch",
    "version": "3.3.2",
    "license": "MIT"
  },
  {
    "name": "once",
    "version": "1.4.0",
    "license": "ISC"
  },
  {
    "name": "openai",
    "version": "6.26.0",
    "license": "Apache-2.0"
  },
  {
    "name": "p-retry",
    "version": "4.6.2",
    "license": "MIT"
  },
  {
    "name": "package-manager-detector",
    "version": "1.7.0",
    "license": "MIT"
  },
  {
    "name": "parse-entities",
    "version": "4.0.2",
    "license": "MIT"
  },
  {
    "name": "parse5",
    "version": "7.3.0",
    "license": "MIT"
  },
  {
    "name": "partial-json",
    "version": "0.1.7",
    "license": "MIT"
  },
  {
    "name": "path-data-parser",
    "version": "0.1.0",
    "license": "MIT"
  },
  {
    "name": "path-exists",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "picocolors",
    "version": "1.1.1",
    "license": "ISC"
  },
  {
    "name": "points-on-curve",
    "version": "0.2.0",
    "license": "MIT"
  },
  {
    "name": "points-on-path",
    "version": "0.2.1",
    "license": "MIT"
  },
  {
    "name": "prebuild-install",
    "version": "7.1.3",
    "license": "MIT"
  },
  {
    "name": "progress",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "property-information",
    "version": "7.2.0",
    "license": "MIT"
  },
  {
    "name": "protobufjs",
    "version": "7.6.5",
    "license": "BSD-3-Clause"
  },
  {
    "name": "pump",
    "version": "3.0.4",
    "license": "MIT"
  },
  {
    "name": "pupa",
    "version": "3.3.0",
    "license": "MIT"
  },
  {
    "name": "rc",
    "version": "1.2.8",
    "license": "(BSD-2-Clause OR MIT OR Apache-2.0)"
  },
  {
    "name": "react",
    "version": "19.2.7",
    "license": "MIT"
  },
  {
    "name": "react-dom",
    "version": "19.2.7",
    "license": "MIT"
  },
  {
    "name": "react-is",
    "version": "19.2.7",
    "license": "MIT"
  },
  {
    "name": "react-redux",
    "version": "9.3.0",
    "license": "MIT"
  },
  {
    "name": "readable-stream",
    "version": "3.6.2",
    "license": "MIT"
  },
  {
    "name": "recharts",
    "version": "3.9.2",
    "license": "MIT"
  },
  {
    "name": "redux",
    "version": "5.0.1",
    "license": "MIT"
  },
  {
    "name": "redux-thunk",
    "version": "3.1.0",
    "license": "MIT"
  },
  {
    "name": "reflect-metadata",
    "version": "0.2.2",
    "license": "Apache-2.0"
  },
  {
    "name": "rehype-harden",
    "version": "1.1.8",
    "license": "MIT"
  },
  {
    "name": "rehype-raw",
    "version": "7.0.0",
    "license": "MIT"
  },
  {
    "name": "rehype-sanitize",
    "version": "6.0.0",
    "license": "MIT"
  },
  {
    "name": "remark-gfm",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "remark-parse",
    "version": "11.0.0",
    "license": "MIT"
  },
  {
    "name": "remark-rehype",
    "version": "11.1.2",
    "license": "MIT"
  },
  {
    "name": "remark-stringify",
    "version": "11.0.0",
    "license": "MIT"
  },
  {
    "name": "remend",
    "version": "1.3.0",
    "license": "Apache-2.0"
  },
  {
    "name": "reselect",
    "version": "5.2.0",
    "license": "MIT"
  },
  {
    "name": "retry",
    "version": "0.13.1",
    "license": "MIT"
  },
  {
    "name": "robust-predicates",
    "version": "3.0.3",
    "license": "Unlicense"
  },
  {
    "name": "roughjs",
    "version": "4.6.6",
    "license": "MIT"
  },
  {
    "name": "rw",
    "version": "1.3.3",
    "license": "BSD-3-Clause"
  },
  {
    "name": "safe-buffer",
    "version": "5.2.1",
    "license": "MIT"
  },
  {
    "name": "safer-buffer",
    "version": "2.1.2",
    "license": "MIT"
  },
  {
    "name": "scheduler",
    "version": "0.27.0",
    "license": "MIT"
  },
  {
    "name": "semver",
    "version": "7.8.5",
    "license": "ISC"
  },
  {
    "name": "simple-concat",
    "version": "1.0.1",
    "license": "MIT"
  },
  {
    "name": "simple-get",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "slice-ansi",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "sort-keys",
    "version": "1.1.2",
    "license": "MIT"
  },
  {
    "name": "sort-keys-length",
    "version": "1.0.1",
    "license": "MIT"
  },
  {
    "name": "space-separated-tokens",
    "version": "2.0.2",
    "license": "MIT"
  },
  {
    "name": "streamdown",
    "version": "2.5.0",
    "license": "Apache-2.0"
  },
  {
    "name": "string_decoder",
    "version": "1.3.0",
    "license": "MIT"
  },
  {
    "name": "string-width",
    "version": "7.2.0",
    "license": "MIT"
  },
  {
    "name": "stringify-entities",
    "version": "4.0.4",
    "license": "MIT"
  },
  {
    "name": "strip-ansi",
    "version": "7.2.0",
    "license": "MIT"
  },
  {
    "name": "strip-json-comments",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "style-to-js",
    "version": "1.1.21",
    "license": "MIT"
  },
  {
    "name": "style-to-object",
    "version": "1.0.14",
    "license": "MIT"
  },
  {
    "name": "stylis",
    "version": "4.4.0",
    "license": "MIT"
  },
  {
    "name": "sumchecker",
    "version": "3.0.1",
    "license": "Apache-2.0"
  },
  {
    "name": "tailwind-merge",
    "version": "3.6.0",
    "license": "MIT"
  },
  {
    "name": "tar-fs",
    "version": "2.1.5",
    "license": "MIT"
  },
  {
    "name": "tar-stream",
    "version": "2.2.0",
    "license": "MIT"
  },
  {
    "name": "tiny-invariant",
    "version": "1.3.3",
    "license": "MIT"
  },
  {
    "name": "tinyexec",
    "version": "1.2.4",
    "license": "MIT"
  },
  {
    "name": "trim-lines",
    "version": "3.0.1",
    "license": "MIT"
  },
  {
    "name": "trough",
    "version": "2.2.0",
    "license": "MIT"
  },
  {
    "name": "ts-algebra",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "ts-dedent",
    "version": "2.3.0",
    "license": "MIT"
  },
  {
    "name": "tslib",
    "version": "1.14.1",
    "license": "0BSD"
  },
  {
    "name": "tslib",
    "version": "2.8.1",
    "license": "0BSD"
  },
  {
    "name": "tsyringe",
    "version": "4.10.0",
    "license": "MIT"
  },
  {
    "name": "tunnel-agent",
    "version": "0.6.0",
    "license": "Apache-2.0"
  },
  {
    "name": "typebox",
    "version": "1.1.38",
    "license": "MIT"
  },
  {
    "name": "typebox",
    "version": "1.3.6",
    "license": "MIT"
  },
  {
    "name": "undici",
    "version": "7.28.0",
    "license": "MIT"
  },
  {
    "name": "undici-types",
    "version": "7.18.2",
    "license": "MIT"
  },
  {
    "name": "undici-types",
    "version": "8.3.0",
    "license": "MIT"
  },
  {
    "name": "unified",
    "version": "11.0.5",
    "license": "MIT"
  },
  {
    "name": "unist-util-is",
    "version": "6.0.1",
    "license": "MIT"
  },
  {
    "name": "unist-util-position",
    "version": "5.0.0",
    "license": "MIT"
  },
  {
    "name": "unist-util-stringify-position",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "unist-util-visit",
    "version": "5.1.0",
    "license": "MIT"
  },
  {
    "name": "unist-util-visit-parents",
    "version": "6.0.2",
    "license": "MIT"
  },
  {
    "name": "unused-filename",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "use-sync-external-store",
    "version": "1.6.0",
    "license": "MIT"
  },
  {
    "name": "util-deprecate",
    "version": "1.0.2",
    "license": "MIT"
  },
  {
    "name": "uuid",
    "version": "14.0.1",
    "license": "MIT"
  },
  {
    "name": "vfile",
    "version": "6.0.3",
    "license": "MIT"
  },
  {
    "name": "vfile-location",
    "version": "5.0.3",
    "license": "MIT"
  },
  {
    "name": "vfile-message",
    "version": "4.0.3",
    "license": "MIT"
  },
  {
    "name": "victory-vendor",
    "version": "37.3.6",
    "license": "MIT AND ISC"
  },
  {
    "name": "web-namespaces",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "web-streams-polyfill",
    "version": "3.3.3",
    "license": "MIT"
  },
  {
    "name": "wrappy",
    "version": "1.0.2",
    "license": "ISC"
  },
  {
    "name": "ws",
    "version": "8.21.1",
    "license": "MIT"
  },
  {
    "name": "yaml",
    "version": "2.9.0",
    "license": "ISC"
  },
  {
    "name": "zod",
    "version": "4.4.3",
    "license": "MIT"
  },
  {
    "name": "zod-to-json-schema",
    "version": "3.25.2",
    "license": "ISC"
  },
  {
    "name": "zwitch",
    "version": "2.0.4",
    "license": "MIT"
  }
];
