// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from "react-router"

// Imports for page components
import * as SyncComponent0 from "./pages/[...fallback].sync"
import * as SyncComponent1 from "./pages/about.sync"
import * as SyncComponent2 from "./pages/charts/[id].sync"
import * as SyncComponent3 from "./pages/charts/index.sync"
import * as SyncComponent4 from "./pages/chat.sync"
import * as SyncComponent5 from "./pages/logs.sync"
import * as SyncComponent6 from "./pages/overview.sync"
import * as SyncComponent7 from "./pages/popout/symbol/[sym].sync"
import * as SyncComponent8 from "./pages/research/index.sync"
import * as SyncComponent9 from "./pages/settings.sync"
import * as SyncComponent10 from "./pages/symbol/[sym].sync"
import * as SyncComponent11 from "./pages/symbol/sepa/[sym].sync"
import * as SyncComponent12 from "./pages/index.sync"

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "*",
    "Component": SyncComponent0.Component,
    "loader": SyncComponent0.loader,
    "handle": SyncComponent0.handle
  },
  {
    "path": "about",
    "Component": SyncComponent1.Component,
    "loader": SyncComponent1.loader,
    "handle": SyncComponent1.handle
  },
  {
    "path": "charts",
    "children": [
      {
        "path": ":id",
        "Component": SyncComponent2.Component,
        "loader": SyncComponent2.loader,
        "handle": SyncComponent2.handle
      },
      {
        "path": "",
        "Component": SyncComponent3.Component,
        "loader": SyncComponent3.loader,
        "handle": SyncComponent3.handle
      }
    ]
  },
  {
    "path": "chat",
    "Component": SyncComponent4.Component,
    "loader": SyncComponent4.loader,
    "handle": SyncComponent4.handle
  },
  {
    "path": "logs",
    "Component": SyncComponent5.Component,
    "loader": SyncComponent5.loader,
    "handle": SyncComponent5.handle
  },
  {
    "path": "overview",
    "Component": SyncComponent6.Component,
    "loader": SyncComponent6.loader,
    "handle": SyncComponent6.handle
  },
  {
    "path": "popout",
    "children": [
      {
        "path": "symbol",
        "children": [
          {
            "path": ":sym",
            "Component": SyncComponent7.Component,
            "loader": SyncComponent7.loader,
            "handle": SyncComponent7.handle
          }
        ]
      }
    ]
  },
  {
    "path": "research",
    "children": [
      {
        "path": "",
        "Component": SyncComponent8.Component,
        "loader": SyncComponent8.loader,
        "handle": SyncComponent8.handle
      }
    ]
  },
  {
    "path": "settings",
    "Component": SyncComponent9.Component,
    "loader": SyncComponent9.loader,
    "handle": SyncComponent9.handle
  },
  {
    "path": "symbol",
    "children": [
      {
        "path": ":sym",
        "Component": SyncComponent10.Component,
        "loader": SyncComponent10.loader,
        "handle": SyncComponent10.handle
      },
      {
        "path": "sepa",
        "children": [
          {
            "path": ":sym",
            "Component": SyncComponent11.Component,
            "loader": SyncComponent11.loader,
            "handle": SyncComponent11.handle
          }
        ]
      }
    ]
  },
  {
    "path": "",
    "Component": SyncComponent12.Component,
    "loader": SyncComponent12.loader,
    "handle": SyncComponent12.handle
  }
]

export default routes
