// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from "react-router"

// Imports for page components
const lazy0 = () => import("./pages/[...fallback]")
const lazy1 = () => import("./pages/about")
const lazy2 = () => import("./pages/charts/[id]")
const lazy3 = () => import("./pages/charts/index")
const lazy4 = () => import("./pages/chat")
const lazy5 = () => import("./pages/logs")
const lazy6 = () => import("./pages/overview")
const lazy7 = () => import("./pages/popout/symbol/[sym]")
const lazy8 = () => import("./pages/research/assistant")
const lazy9 = () => import("./pages/research/index")
const lazy10 = () => import("./pages/settings")
const lazy11 = () => import("./pages/symbol/[sym]")
const lazy12 = () => import("./pages/symbol/sepa/[sym]")
const lazy13 = () => import("./pages/index")

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "*",
    "lazy": lazy0
  },
  {
    "path": "about",
    "lazy": lazy1
  },
  {
    "path": "charts",
    "children": [
      {
        "path": ":id",
        "lazy": lazy2
      },
      {
        "path": "",
        "lazy": lazy3
      }
    ]
  },
  {
    "path": "chat",
    "lazy": lazy4
  },
  {
    "path": "logs",
    "lazy": lazy5
  },
  {
    "path": "overview",
    "lazy": lazy6
  },
  {
    "path": "popout",
    "children": [
      {
        "path": "symbol",
        "children": [
          {
            "path": ":sym",
            "lazy": lazy7
          }
        ]
      }
    ]
  },
  {
    "path": "research",
    "children": [
      {
        "path": "assistant",
        "lazy": lazy8
      },
      {
        "path": "",
        "lazy": lazy9
      }
    ]
  },
  {
    "path": "settings",
    "lazy": lazy10
  },
  {
    "path": "symbol",
    "children": [
      {
        "path": ":sym",
        "lazy": lazy11
      },
      {
        "path": "sepa",
        "children": [
          {
            "path": ":sym",
            "lazy": lazy12
          }
        ]
      }
    ]
  },
  {
    "path": "",
    "lazy": lazy13
  }
]

export default routes
