import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(appRoot, "..");

const raw = execFileSync("pnpm", ["licenses", "list", "--json", "-P"], {
  cwd: appRoot,
  encoding: "utf8",
  maxBuffer: 64 * 1024 * 1024,
});

const byLicense = JSON.parse(raw);
const entries = [];
for (const [license, packages] of Object.entries(byLicense)) {
  for (const pkg of packages) {
    for (const version of pkg.versions ?? []) {
      entries.push({ name: pkg.name, version, license });
    }
  }
}
entries.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const creditsTs = `export type CreditEntry = { name: string; version: string; license: string };

export const CREDITS: CreditEntry[] = ${JSON.stringify(entries, null, 2)};
`;

const licenseText = readFileSync(join(repoRoot, "LICENSE"), "utf8");
const licenseTs = `export const LICENSE_TEXT = ${JSON.stringify(licenseText)};
`;

const header = "// Generated by scripts/generate-credits.mjs — do not edit. Refresh with `pnpm credits`.\n";
writeFileSync(join(appRoot, "shared/credits.ts"), header + creditsTs);
writeFileSync(join(appRoot, "shared/licenseText.ts"), header + licenseTs);
console.log(`credits: ${entries.length} packages`);
